image: node:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building"
    - cd front-end
    - npm install --legacy-peer-deps
    - CI=false npm run-script build

test:
  stage: test
  script:
    - cd front-end
    - npm install --legacy-peer-deps
    - yarn test

postman_tests:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - newman run Postman.json

selenium_tests:
  stage: test
  image: python:3.6-stretch
  before_script:
    - pip3 install -r front-end/src/gui_tests/requirements.txt
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install ./google-chrome-stable_current_amd64.deb
    - chmod a+x "./front-end/src/gui_tests/chromedriver_linux"
  script:
    - python3 front-end/guitests.py

deploy_develop:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "back-end"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - git checkout back-end
  script:
    - cd back-end
    - /root/.local/bin/eb deploy environment-name

deploy_production:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - git checkout main
  script:
    - cd back-end
    - /root/.local/bin/eb deploy environment-name

