image: node:14

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cd front-end
    - npm install --legacy-peer-deps
    - CI=false npm run-script build

test:
  stage: test
  script:
    - cd front-end
    - npm install --legacy-peer-deps
    - yarn test

postman_tests:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - newman run Postman.json

selenium_tests:
  stage: test
  image: bhinh/selenium
  before_script:
    - pip3 install -r front-end/src/gui_tests/requirements.txt
    - chmod a+x "./front-end/src/gui_tests/chromedriver_linux"
  script:
    - python3 front-end/guitests.py
    
python_unit_tests:
  image: python:3.8
  stage: test
  before_script:
    - pip install -r back-end/requirements.txt
  script:
    - cd back-end
    - pytest


deploy_develop:
  image: python:3.8
  only:
    variables:
      - $CI_COMMIT_BRANCH == "back-end"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - git checkout back-end --no-guess
  script:
    - cd back-end
    - /root/.local/bin/eb deploy environment-name

deploy_production:
  image: python:3.8
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - git checkout main
  script:
    - cd back-end
    - /root/.local/bin/eb deploy environment-name

