branch-defaults:
  default:
    environment: environment-name
    group_suffix: null
environment-defaults:
  environment-name:
    branch: null
    repository: null
global:
  application_name: campus-catalog
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
